name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Configure github-actions[bot]
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Commit build output
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Merge build output [skip-ci]
