name: CI

on:
  push:
    branches:
      - playground

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: rav2040/test-playground-action@main
        id: one

      - run: echo ${{ steps.one.outputs.foo }}
